# .streamlit/secrets.toml

# Gemini API 키
# gemini_api_key = "AIzaSyAWoXUaaePX_GE0p_7_lE0MT97UL-zAOC4"
gemini_api_key = "AIzaSyCE4ih0COgi62CPB9BQxR-MKZGaiBeelCU"

# 구글 서비스 계정 키 
[gcp_service_account]
type = "service_account"
project_id = "medilens-483701"
private_key_id = "f4bcf876eb5a84e8d6ad8387a4d8c6e1f93c0e43"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCU+YL5vgf8p94p\nVuuxMMNCwRSk1AQILyjUYYFBi/sxKryx/kON2O59AoqhpEBnS7vUQaiCISPk4hrW\nOtd6h0P5FC98p0Cw3T4NQ3xYlooJsexPhHLOlsTC8GauK5ad3ww3KZ23Ow5xfpdK\nsSGzbfSAZMmSy8jYtkd6n6FjpB1QucY7cO9Y3zneWcQQIS/cYl+gKv+vmWBkoMYk\n3imkqHcHmqR8/MQe+iOPyzsU7aAiivtkPq04e6XkcusqvABDUvlna0mBpqW+8tOe\nU9A0ogPnVDsKR6Xzbviq/lq8TSX/Odrk4kodasbe1kkL7VfbdHY4d1L7YSfRAY6W\nyt3gjsi1AgMBAAECggEAMH4r0Um3Zdnq6j/+BradyNv68VCGY3eebcuzfHepc666\nr6HZsZG8x/qMz+Mch8NSR9x7kqhg+79SBwwuWhcv3CNi9cuntiq+aSjfkCKomlFN\nX/D4QiE3uVDxy54qsAcL/eTRDvTtVapkaw7Pro2LOkQUjXFCVrC3AcZ2jW29kSn4\noHLm4V7rrxVyOTwAZnmFYCcUo6BRRR35dNE+W095KfChqp1UEdy6FoKhN3gvuBYQ\nfXdmnd2KrKkuEebnYDAt2aw/ycpqAddVJTMDK0kpqZJ3mVRhszwlDBpgsRtoiosg\nF9KXxORWX3evfL1hZZTOB8LXyjoBBb/ljfLxUtKw3QKBgQDHHdMTJ1RwZ6yQlmqj\nXTqwrsJvEFHYcnjW7yaETphafbnPCe5PnPuF0pRBaISgKLRqMx36hx2CPKhR5Z6v\nATe07GOkM/COiZbukb2Ke878LyhCi2e7DnsFtdvHzFv7hMgCSl3AHSym5/3qjTDM\n9Xspbt4G41cQ6LCFA0hxJmpo/wKBgQC/iJ2wLG60tAUcWtufLN7kXBi9/5fr6g2N\nFjhxF7xqnmzPBsE82UAaDudF+C++p9ftoo4H3fJPpUwPWdCuTnvqow+xOzRe/ZDm\nU6mHOjfng5wAnDQQAOc5uD2yZVzZC6zLnri4hRVeeb4W2U2x+K4A4Sgd6pXN/09U\naUZcSif6SwKBgFUg0CQpNXWVLXbniBHuAvCU1rXLIWLLlhQ2TJ5WR9awV+dHVKae\n8/4DyLSqLcGXhYK99fwtFhWfP0s8Q3qIp7tnMTZ7qkYWVvwKPSHeyuCQfMLufNvB\nViFb3enu2giPfT9Vcf13u6ZkGu/Ti2ClNxHAv5XsTkYBZa6Id8lAZlAbAoGATj9r\n3ItqdtyMsfbUfoUAUl7lpMmEsVafTqJjUKCX0x8B6Nojm85Nh9fK2CT6rHM5ndWp\nHMGpuqwXFLZmsK9TpJoVURyU2rHQvqgzPBGmwShdVUp7YoZb8JK6ceVDN1CzuUQQ\nxyFnh39JD2CbgzfLLoTNtNsfdFb3e86+dfm9t10CgYBhIOatX/8WYXvmh9/gOovy\nKJyUpx8gHzQduFpMxKYhy3qGkmPWDldR+bEe/yMtYondpaEb9UXURPeWz3wEGkdw\nBF8QpYhwjHUxfx7bU7JMXfSN0X9MHsH4uJUBDjseak9+T1kgud3mvb+doFuRyEMp\nq63yeibAY27ZHGfEeDU0ng==\n-----END PRIVATE KEY-----\n"
client_email = "medilens@medilens-483701.iam.gserviceaccount.com"
client_id = "101156788257158705423"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/medilens%40medilens-483701.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

[public_data_portal]
api_key = "7398c2fbfe7a3c01ed88d38de56954d2b18e8e875d8bdfaaf29b9593a917a726"